spring:
  datasource:
    druid:
      #下面的内容不需要修改，这些都是我的远程数据库
      username: root
      password: machaojin
      url: jdbc:mysql://101.42.149.76:3306/boke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 101.42.149.76
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
  thymeleaf:
    cache: false
    mode: HTML5
    #配置i18n文件
  messages:
    basename: i18n/login
  mvc:
    format:
      time: HH:mm:ss
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl