spring:
  datasource:
    druid:
      username: root
      password: machaojin
      url: jdbc:mysql://localhost:3306/spring-boot?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 101.42.149.76
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
  thymeleaf:
    cache: false
    mode: HTML5
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.jdk14.Jdk14LoggingImpl